# Site setting
# 
# to test on local system, type:
#   > bundle exec jekyll serve
# and open web-browser at:
#   http://127.0.0.1:4000
# 

## infos
title: SPECFEM 
description: > # this means to ignore newlines until "baseurl:"
 A family of spectral-element method software codes for computational seismology. 

## more infos
#email: your-email@domain.com
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://specfem.org" # the base hostname & protocol for your site
twitter_username: specfem
#github_username:  jekyll

## Build settings
#markdown: kramdown

## Themes
#theme: minima
#theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

## Gems
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

